// THIS FILE IS AUTO-GENERATED

export enum Category {
  FOOD = "FOOD",
  TRANSPORTATION = "TRANSPORTATION",
  SHOPPING = "SHOPPING",
  ENTERTAINMENT = "ENTERTAINMENT",
  BILLS = "BILLS",
  HEALTH = "HEALTH",
  LEARNING = "LEARNING",
  INVESTMENT = "INVESTMENT",
  INSURANCE = "INSURANCE",
  RENTAL = "RENTAL",
  TAXES = "TAXES",
  CHARITY = "CHARITY",
  GIFT = "GIFT",
  FAMILY = "FAMILY",
  TRAVEL = "TRAVEL",
  OTHER = "OTHER",
}

export enum Currency {
  USD = "USD",
  JPY = "JPY",
  TWD = "TWD",
}

export enum Frequency {
  ONE_TIME = "ONE_TIME",
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  ANNUALLY = "ANNUALLY",
}

export enum NotificationFrequency {
  ONE_DAY_BEFORE = "ONE_DAY_BEFORE",
  ONE_WEEK_BEFORE = "ONE_WEEK_BEFORE",
  ONE_MONTH_BEFORE = "ONE_MONTH_BEFORE",
  NONE = "NONE",
}
